#!/bin/bash
_curr=$(git rev-parse --abbrev-ref HEAD)

_git_origin="${1:-${_curr}}"
echo "Pushing latest changes to repo '${_git_origin}'..."

read -p "Commit Description: " desc

if [[ $desc ]]
    then
	git add . && \
	git add -u && \
	git commit -m "$desc" && \
	git push origin ${_git_origin}
else
	echo "Could not commit. No commit description provided."
fi
